#!/usr/bin/env bash

sm2 --start API_DEFINITION THIRD_PARTY_APPLICATION THIRD_PARTY_DEVELOPER API_EXAMPLE_MICROSERVICE API_PLATFORM_MICROSERVICE THIRD_PARTY_DEVELOPER_FRONTEND CONTACT_FRONTEND API_PLATFORM_XML_SERVICES


./run_local.sh
