#%RAML 1.0 Library

usage: Collection of common annotations

annotationTypes:
  config: object
  group:
    type: object
    properties:
      name: string
      description: string
  scope:
  fieldOptionalityUnknown: nil
  sandboxData:
  deprecationMessage:
  documentation:
