#%RAML 1.0 Library

usage: Collection of common headers

traits:
  acceptHeader:
    headers:
      Accept:
        description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
        type: string
        required: true
        example: application/vnd.hmrc.1.0+json

  contentHeader:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
