#%RAML 1.0
---
title: Single method
version: 1.0

types:
  myEnumType:
    enum: ["a", "b", "c"]

/my/endpoint:
    get:
      description: My description
      displayName: My endpoint

      queryParameters:
        aParam:
          type:
            enum: ["1","2"]
        anotherParam:
          type: myEnumType
