#%RAML 1.0
---

title: Business Rates
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  paged: !include traits/paged.raml
  pagedProperties: !include traits/pagedProperties.raml
  sortable: !include traits/sortable.raml

/organisations/business-rates:
  /property-search:
    get:
      displayName: Search for properties
      description: !include endpoints/property-search/overview.md
      is: [headers.acceptHeader, pagedProperties]
      (annotations.scope): "all:business-rates"
      securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
      queryParameters:
        postcode:
          type: string
          description: Filters the results to include properties which match the provided postcode. The search is not case sensitive and must contain the 'Outward Code' (e.g. RH1). This, or at least one other search parameter, must be included in your search.
          required: false
        billingAuthorityReference:
          type: string
          description: Filters the results to include properties which are inside the provided billing authority. The search is not case sensitive and supports partial references. This, or at least one other search parameter, must be included in your search.
          required: false
        uarn:
          type: string
          description: Filters the results down to a single property with the given UARN. This, or at least one other search parameter, must be included in your search.
          required: false
      responses:
        200:
          body:
            application/json:
              type: !include endpoints/property-search/schemas/property-search-response-schema.json
              examples:
                example-1:
                  value: !include endpoints/property-search/examples/property-search-response-example.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                example-1:
                  description: If the provided query parameters don't match the specification.
                  value:
                    code: BAD_REQUEST
  /properties:
    /{uarn}/valuations:
      uriParameters:
        uarn:
          description: The Unique Address Reference Number (UARN) of the property
          type: number
          example: 12345678901
          required: true
      get:
        displayName: Get valuation history
        description: !include endpoints/properties/valuations/valuation-history-overview.md
        is: [headers.acceptHeader]
        (annotations.scope): "all:business-rates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
        queryParameters:
          propertyLinkSubmissionId:
            description: The property link you wish to filter the history on.
            type: string
            example: PL123456
            required: false
        responses:
          200:
            body:
              application/json:
                type: !include endpoints/properties/valuations/schemas/valuation-history-response-schema.json
                examples:
                  example-1:
                    value: !include endpoints/properties/valuations/examples/valuation-history-response-example.json
          404:
             body:
              application/json:
                type: types.errorResponse
                examples:
                  valuationNotFound:
                    description: The UARN does not exist.
                    code: NOT_FOUND
      /{valuationId}:
        uriParameters:
          valuationId:
            description: The valuation ID.
            type: number
            example: 12345678901
            required: true
        get:
          displayName: Get valuation
          description: !include endpoints/properties/valuations/valuation-overview.md
          is: [headers.acceptHeader]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
              projection:
                type: string
                enum: ["summary", "detailed"]
                description: Currently only accepts 'summary' and 'detailed' projection.
                required: true
              propertyLinkSubmissionId:
                type: string
                description: The property link Id of the property you wish to view (required with projection=detailed).
                required: false
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/properties/valuations/schemas/summary-valuation-response-schema.json
                  examples:
                    summary:
                      strict: true
                      description: Summary Valuation (?projection=summary)
                      value: !include endpoints/properties/valuations/examples/summary-valuation-response-example.json
                    detailed-licensed-premises:
                      strict: false
                      description: Detailed Valuation for licensed Premises. (?projection=detailed)
                      value: !include endpoints/properties/valuations/examples/detailed-valuation-lp-response-example.json
                    detailed-bulk:
                      strict: false
                      description: Detailed Valuation for Bulk Properties. (?projection=detailed)
                      value: !include endpoints/properties/valuations/examples/detailed-valuation-bulk-response-example.json
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    valuationNotFound:
                      description: A summary valuation does not exist for the provided ID.
                      value:
                        code: NOT_FOUND
  /my-organisation:
      /property-links:
        post:
          displayName: Create property link
          description: !include endpoints/my-organisation/property-links/create-property-link-overview.md
          is: [headers.acceptHeader, headers.contentHeader]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
          body:
            application/json:
              type: !include endpoints/my-organisation/property-links/schemas/create-property-link-request-schema.json
              example: !include endpoints/my-organisation/property-links/examples/create-property-link-request-example.json
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/my-organisation/property-links/schemas/create-property-link-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/property-links/examples/create-property-link-response-example.json
        get:
          displayName: Get my organisation's property links
          description: !include endpoints/my-organisation/property-links/get-my-organisations-property-links-overview.md
          is: [headers.acceptHeader, paged, sortable]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
            address:
              type: string
              description: Address, or part of the address (e.g. street name or postcode), to filter by
              required: false
              maxLength: 1000
            uarn:
              description: The Unique Address Reference Number (UARN) of the property
              type: number
              example: 12345678901
              required: false
            billingAuthorityReference:
              type: string
              description: Filters the results to include properties which are inside the provided billing authority.
              required: true
            status:
              type: string
              enum: ["APPROVED", "PENDING", "DECLINED", "REVOKED", "MORE_EVIDENCE_REQUIRED"]
              description: The status of a property link to filter by
              required: false
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/my-organisation/property-links/schemas/my-organisations-property-links-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/property-links/examples/my-organisations-property-links-example.json
        /{propertyLinkSubmissionId}:
         get:
          displayName: Get my organisations property link
          description: !include endpoints/my-organisation/property-links/get-my-organisations-property-link-overview.md
          is: [headers.acceptHeader]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
            projection:
              type: string
              enum: ["summary", "detailed"]
              description: Currently accepts 'summary' and 'detailed' projection. Defaults to 'summary'.
              required: false
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/my-organisation/property-links/schemas/my-organisations-summary-property-link-response-schema.json
                  examples:
                    summary:
                      strict: true
                      description: Summary Property Link (?projection=summary)
                      value: !include endpoints/my-organisation/property-links/examples/my-organisations-summary-property-link-example.json
                    detailed:
                      strict: false
                      description: Detailed Property Link (?projection=detailed)
                      value: !include endpoints/my-organisation/property-links/examples/my-organisations-detailed-property-link-example.json
         /evidence:
           post:
             displayName: Attach property link evidence
             description: !include endpoints/my-organisation/property-links/attach-property-link-evidence-overview.md
             is: [headers.acceptHeader]
             (annotations.scope): "all:business-rates"
             securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
             queryParameters:
             body:
               application/json:
                 type: !include endpoints/my-organisation/property-links/schemas/attach-property-link-evidence-request-schema.json
                 example: !include endpoints/my-organisation/property-links/examples/attach-property-link-evidence-request-example.json
             responses:
               200:
                 body:
                   application/json:
                     type: !include endpoints/my-organisation/property-links/schemas/attach-property-link-evidence-response-schema.json
                     examples:
                       example-1:
                         value: !include endpoints/my-organisation/property-links/examples/attach-property-link-evidence-response-example.json
           /{evidenceReference}:
            get:
              displayName: Retrieve status of property link evidence
              description: !include endpoints/my-organisation/property-links/get-property-link-evidence-overview.md
              is: [headers.acceptHeader]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/property-links/schemas/get-property-link-evidence-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/property-links/examples/get-property-link-evidence-response-example.json
      /check-cases:
        get:
          displayName: Get my organisation's check cases
          description: !include endpoints/my-organisation/check-cases/get-check-cases-overview.md
          is: [headers.acceptHeader, paged]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
            propertyLinkSubmissionId:
              type: string
              description: The property link you wish to filter on.
              required: true
              pattern: ^\w[\S]{1,44}$
            checkCaseStatus:
              type: string
              enum: ["RECEIVED", "PENDING", "ASSIGNED", "OPEN", "DECISION_SENT", "UNDER_REVIEW", "CLOSED", "CANCELLED"]
              description: The check case status you wish to filter on.
              required: false
            checkCaseReference:
              type: string
              description: The check case reference you wish to filter on.
              required: false
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/my-organisation/check-cases/schemas/get-my-organisation-check-cases-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/check-cases/examples/get-my-organisation-check-cases-response-example.json
        post:
          displayName: Create a check case
          description: !include endpoints/my-organisation/check-cases/create-check-case-overview.md
          is: [headers.acceptHeader]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
          body:
            application/json:
              type: !include endpoints/my-organisation/check-cases/schemas/create-check-case-request-schema.json
              examples:
                example-1:
                  strict: false
                  value: !include endpoints/my-organisation/check-cases/examples/create-check-case-request-bulk-example.json
                example-2:
                  strict: false
                  value: !include endpoints/my-organisation/check-cases/examples/create-check-case-request-lp-example.json
          responses:
            202:
              body:
                application/json:
                  type: !include endpoints/my-organisation/check-cases/schemas/create-check-case-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/check-cases/examples/create-check-case-response-example.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    example-1:
                      description: If the year built is after year refurbished.
                      value:
                        code: BAD_REQUEST
                    example-2:
                      description: If the year refurbished is before year built.
                      value:
                        code: BAD_REQUEST
        /{checkCaseSubmissionId}:
          get:
            displayName: Get my organisation's check case
            description: !include endpoints/my-organisation/check-cases/get-check-case-overview.md
            is: [headers.acceptHeader]
            (annotations.scope): "all:business-rates"
            securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
            queryParameters:
              propertyLinkSubmissionId:
                type: string
                description: The property link you wish to filter on.
                required: true
                pattern: ^\w[\S]{1,44}$
            responses:
              200:
                body:
                  application/json:
                    type: !include endpoints/my-organisation/check-cases/schemas/get-my-organisation-check-case-response-schema.json
                    examples:
                      example-1:
                        value: !include endpoints/my-organisation/check-cases/examples/get-my-organisation-check-case-response-example.json
          /evidence:
            post:
              displayName: Attach check case evidence
              description: !include endpoints/my-organisation/check-cases/attach-check-case-evidence-overview.md
              is: [headers.acceptHeader]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
              body:
                application/json:
                  type: !include endpoints/my-organisation/check-cases/schemas/attach-check-case-evidence-request-schema.json
                  example: !include endpoints/my-organisation/check-cases/examples/attach-check-case-evidence-request-example.json
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/check-cases/schemas/attach-check-case-evidence-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/check-cases/examples/attach-check-case-evidence-response-example.json
            /{evidenceReference}:
              get:
                displayName: Retrieve status of check case evidence
                description: !include endpoints/my-organisation/check-cases/get-check-case-evidence-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                responses:
                  200:
                    body:
                      application/json:
                        type: !include endpoints/my-organisation/check-cases/schemas/get-check-case-evidence-response-schema.json
                        examples:
                          example-1:
                            value: !include endpoints/my-organisation/check-cases/examples/get-check-case-evidence-response-example.json
      /challenge-cases:
        get:
          displayName: Get my organisation's challenge cases
          description: !include endpoints/my-organisation/challenge-cases/get-challenge-cases-overview.md
          is: [headers.acceptHeader, paged]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
            propertyLinkSubmissionId:
              type: string
              description: The property link you wish to filter on.
              required: true
              pattern: ^\w[\S]{1,44}$
          responses:
            200:
              body:
                application/json:
                  type: !include endpoints/my-organisation/challenge-cases/schemas/get-challenge-cases-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/challenge-cases/examples/get-challenge-cases-response-example.json
        post:
          displayName: Create a challenge case
          description: !include endpoints/my-organisation/challenge-cases/create-challenge-case-overview.md
          is: [headers.acceptHeader]
          (annotations.scope): "all:business-rates"
          securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
          queryParameters:
          body:
            application/json:
              type: !include endpoints/my-organisation/challenge-cases/schemas/create-challenge-case-request-schema.json
              examples:
                example-1:
                  strict: false
                  value: !include endpoints/my-organisation/challenge-cases/examples/create-challenge-case-request-example.json
          responses:
            202:
              body:
                application/json:
                  type: !include endpoints/my-organisation/challenge-cases/schemas/create-challenge-case-response-schema.json
                  examples:
                    example-1:
                      value: !include endpoints/my-organisation/challenge-cases/examples/create-challenge-case-response-example.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    example-1:
                      description: If the challenge submission is not valid.
                      value:
                        code: BAD_REQUEST
        /{challengeCaseSubmissionId}:
          get:
            displayName: Get a challenge case
            description: !include endpoints/my-organisation/challenge-cases/get-challenge-case-overview.md
            is: [headers.acceptHeader]
            (annotations.scope): "all:business-rates"
            securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
            queryParameters:
              projection:
                type: string
                enum: ["summary", "detailed"]
                description: Currently only accepts 'summary' and 'detailed' projection.
                required: true
              propertyLinkSubmissionId:
                type: string
                description: The property link you wish to filter on.
                required: true
                pattern: ^\w[\S]{1,44}$
            responses:
              200:
                body:
                  application/json:
                    type: !include endpoints/my-organisation/challenge-cases/schemas/get-challenge-case-summary-response-schema.json
                    examples:
                      example-1:
                        strict: true
                        description: Summary of a challenge case submission (?projection=summary)
                        value: !include endpoints/my-organisation/challenge-cases/examples/get-challenge-case-summary-response-example.json
                      example-2:
                        strict: false
                        description: Detailed view of a challenge case (?projection=detailed)
                        value: !include endpoints/my-organisation/challenge-cases/examples/get-challenge-case-detailed-response-example.json
        /{challengeCaseSubmissionId}/evidence:
          post:
            displayName: Attach challenge case evidence
            description: !include endpoints/my-organisation/challenge-cases/attach-challenge-case-evidence-overview.md
            is: [headers.acceptHeader]
            (annotations.scope): "all:business-rates"
            securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
            queryParameters:
            body:
              application/json:
                type: !include endpoints/my-organisation/challenge-cases/schemas/attach-challenge-case-evidence-request-schema.json
                example: !include endpoints/my-organisation/challenge-cases/examples/attach-challenge-case-evidence-request-example.json
            responses:
              200:
                body:
                  application/json:
                    type: !include endpoints/my-organisation/challenge-cases/schemas/attach-challenge-case-evidence-response-schema.json
                    examples:
                      example-1:
                        value: !include endpoints/my-organisation/challenge-cases/examples/attach-challenge-case-evidence-response-example.json
          /{evidenceReference}:
             get:
               displayName: Retrieve status of challenge case evidence
               description: !include endpoints/my-organisation/challenge-cases/get-challenge-case-evidence-overview.md
               is: [headers.acceptHeader]
               (annotations.scope): "all:business-rates"
               securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
               queryParameters:
               responses:
                 200:
                   body:
                     application/json:
                       type: !include endpoints/my-organisation/challenge-cases/schemas/get-challenge-case-evidence-response-schema.json
                       examples:
                         example-1:
                           value: !include endpoints/my-organisation/challenge-cases/examples/get-challenge-case-evidence-response-example.json
      /clients:
          get:
            displayName: Get my list of clients
            description: !include endpoints/my-organisation/clients/get-my-clients-overview.md
            is: [headers.acceptHeader, paged]
            (annotations.scope): "all:business-rates"
            securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
            queryParameters:
              clientOrganisation:
                type: string
                description: This parameter allows you to filter your clients by the start of their organisation's name
                required: false
              appointedFromDate:
                type: date-only
                example: 2020-01-31
                description: Filters the results to include only clients appointed on or after this date
                required: false
              appointedToDate:
                type: date-only
                example: 2020-12-31
                description: Filters the results to include only clients appointed on or before this date
                required: false
            responses:
              200:
                body:
                  application/json:
                    type: !include endpoints/my-organisation/clients/schemas/get-my-clients-response-schema.json
                    examples:
                      example-1:
                        value: !include endpoints/my-organisation/clients/examples/get-my-clients-response-example.json
          /all/check-cases:
            get:
              displayName: Get my clients' check cases
              description: !include endpoints/my-organisation/clients/check-cases/get-client-check-cases-overview.md
              is: [headers.acceptHeader, paged]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
                propertyLinkSubmissionId:
                  type: string
                  description: The property link you wish to filter on.
                  required: true
                  pattern: ^\w[\S]{1,44}$
                checkCaseStatus:
                  type: string
                  enum: ["RECEIVED", "PENDING", "ASSIGNED", "OPEN", "DECISION_SENT", "UNDER_REVIEW", "CLOSED", "CANCELLED"]
                  description: The check case status you wish to filter on.
                  required: false
                checkCaseReference:
                  type: string
                  description: The check case reference you wish to filter on.
                  required: false
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/check-cases/schemas/get-clients-check-cases-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/check-cases/examples/get-clients-check-cases-response-example.json
            post:
              displayName: Create a client check case
              description: !include endpoints/my-organisation/clients/check-cases/create-client-check-case-overview.md
              is: [headers.acceptHeader]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
              body:
                application/json:
                  type: !include endpoints/my-organisation/clients/check-cases/schemas/create-client-check-case-request-schema.json
                  examples:
                    example-1:
                      strict: false
                      value: !include endpoints/my-organisation/clients/check-cases/examples/create-client-check-case-request-bulk-example.json
                    example-2:
                      strict: false
                      value: !include endpoints/my-organisation/clients/check-cases/examples/create-client-check-case-request-lp-example.json
              responses:
                202:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/check-cases/schemas/create-client-check-case-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/check-cases/examples/create-client-check-case-response-example.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        example-1:
                          description: If the year built is after year refurbished.
                          value:
                            code: BAD_REQUEST
                        example-2:
                          description: If the year refurbished is before year built.
                          value:
                            code: BAD_REQUEST
            /{checkCaseSubmissionId}:
               get:
                 displayName: Get my clients's check case
                 description: !include endpoints/my-organisation/clients/check-cases/get-client-check-case-overview.md
                 is: [headers.acceptHeader]
                 (annotations.scope): "all:business-rates"
                 securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                 queryParameters:
                 responses:
                   200:
                     body:
                       application/json:
                         type: !include endpoints/my-organisation/clients/check-cases/schemas/get-my-clients-check-case-response-schema.json
                         examples:
                           example-1:
                             value: !include endpoints/my-organisation/clients/check-cases/examples/get-my-clients-check-case-response-example.json
               /evidence:
                post:
                  displayName: Attach check case evidence for clients
                  description: !include endpoints/my-organisation/clients/check-cases/attach-client-check-case-evidence-overview.md
                  is: [headers.acceptHeader]
                  (annotations.scope): "all:business-rates"
                  securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                  queryParameters:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/check-cases/schemas/attach-client-check-case-evidence-request-schema.json
                      example: !include endpoints/my-organisation/clients/check-cases/examples/attach-client-check-case-evidence-request-example.json
                  responses:
                    200:
                      body:
                        application/json:
                          type: !include endpoints/my-organisation/clients/check-cases/schemas/attach-client-check-case-evidence-response-schema.json
                          examples:
                            example-1:
                              value: !include endpoints/my-organisation/clients/check-cases/examples/attach-client-check-case-evidence-response-example.json
                /{evidenceReference}:
                  get:
                    displayName: Retrieve status of check case evidence
                    description: !include endpoints/my-organisation/check-cases/get-check-case-evidence-overview.md
                    is: [headers.acceptHeader]
                    (annotations.scope): "all:business-rates"
                    securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                    queryParameters:
                    responses:
                      200:
                        body:
                          application/json:
                            type: !include endpoints/my-organisation/clients/check-cases/schemas/get-client-check-case-evidence-response-schema.json
                            examples:
                              example-1:
                                value: !include endpoints/my-organisation/clients/check-cases/examples/get-client-check-case-evidence-response-example.json
          /all/challenge-cases:
            get:
              displayName: Get my client's challenge cases
              description: !include endpoints/my-organisation/clients/challenge-cases/get-client-challenge-cases-overview.md
              is: [headers.acceptHeader, paged]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
                propertyLinkSubmissionId:
                  type: string
                  description: The property link you wish to filter on.
                  required: true
                  pattern: ^\w[\S]{1,44}$
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/challenge-cases/schemas/get-client-challenge-cases-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/challenge-cases/examples/get-client-challenge-cases-response-example.json
            post:
              displayName: Create a client challenge case
              description: !include endpoints/my-organisation/clients/challenge-cases/create-client-challenge-case-overview.md
              is: [headers.acceptHeader]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
              body:
                application/json:
                  type: !include endpoints/my-organisation/clients/challenge-cases/schemas/create-client-challenge-case-request-schema.json
                  examples:
                    example-1:
                      strict: false
                      value: !include endpoints/my-organisation/clients/challenge-cases/examples/create-client-challenge-case-request-example.json
              responses:
                202:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/challenge-cases/schemas/create-client-challenge-case-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/challenge-cases/examples/create-client-challenge-case-response-example.json
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                         example-1:
                           description: If the challenge submission is not valid.
                           value:
                             code: BAD_REQUEST
            /{challengeCaseSubmissionId}:
              get:
                displayName: Get a client's challenge case
                description: !include endpoints/my-organisation/clients/challenge-cases/get-client-challenge-case-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                  projection:
                    type: string
                    enum: ["summary", "detailed"]
                    description: Currently only accepts 'summary' and 'detailed' projection.
                    required: true
                  propertyLinkSubmissionId:
                    type: string
                    description: The property link you wish to filter on.
                    required: true
                    pattern: ^\w[\S]{1,44}$
                responses:
                  200:
                    body:
                      application/json:
                        type: !include endpoints/my-organisation/clients/challenge-cases/schemas/get-client-challenge-case-summary-response-schema.json
                        examples:
                          example-1:
                            strict: true
                            description: Summary of a challenge case submission (?projection=summary)
                            value: !include endpoints/my-organisation/clients/challenge-cases/examples/get-client-challenge-case-summary-response-example.json
                          example-2:
                            strict: false
                            description: Detailed view of a challenge case (?projection=detailed)
                            value: !include endpoints/my-organisation/clients/challenge-cases/examples/get-client-challenge-case-detailed-response-example.json
              /evidence:
                post:
                  displayName: Attach challenge case evidence for clients
                  description: !include endpoints/my-organisation/clients/challenge-cases/attach-client-challenge-case-evidence-overview.md
                  is: [headers.acceptHeader]
                  (annotations.scope): "all:business-rates"
                  securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                  queryParameters:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/challenge-cases/schemas/attach-client-challenge-case-evidence-request-schema.json
                      example: !include endpoints/my-organisation/clients/challenge-cases/examples/attach-client-challenge-case-evidence-request-example.json
                  responses:
                    200:
                      body:
                        application/json:
                          type: !include endpoints/my-organisation/clients/challenge-cases/schemas/attach-client-challenge-case-evidence-response-schema.json
                          examples:
                            example-1:
                              value: !include endpoints/my-organisation/clients/challenge-cases/examples/attach-client-challenge-case-evidence-response-example.json
                /{evidenceReference}:
                   get:
                     displayName: Retrieve status of challenge case evidence
                     description: !include endpoints/my-organisation/clients/challenge-cases/get-client-challenge-case-evidence-overview.md
                     is: [headers.acceptHeader]
                     (annotations.scope): "all:business-rates"
                     securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                     queryParameters:
                     responses:
                       200:
                         body:
                           application/json:
                             type: !include endpoints/my-organisation/clients/challenge-cases/schemas/get-client-challenge-case-evidence-response-schema.json
                             examples:
                               example-1:
                                 value: !include endpoints/my-organisation/clients/challenge-cases/examples/get-client-challenge-case-evidence-response-example.json
          /all/property-links:
            post:
              displayName: Create property link on client's behalf
              description: !include endpoints/my-organisation/clients/property-links/create-client-property-link-overview.md
              is: [headers.acceptHeader, headers.contentHeader]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
              body:
                application/json:
                  type: !include endpoints/my-organisation/clients/property-links/schemas/create-client-property-link-request-schema.json
                  example: !include endpoints/my-organisation/clients/property-links/examples/create-client-property-link-request-example.json
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/property-links/schemas/create-client-property-link-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/property-links/examples/create-client-property-link-response-example.json
            get:
              displayName: Get my clients' property links
              description: !include endpoints/my-organisation/clients/property-links/get-my-clients-property-links-overview.md
              is: [headers.acceptHeader, paged, sortable]
              (annotations.scope): "all:business-rates"
              securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
              queryParameters:
                address:
                  type: string
                  description: Address, or part of the address (e.g. street name or postcode), to filter by
                  required: false
                  maxLength: 1000
                uarn:
                  description: The Unique Address Reference Number (UARN) of the property
                  type: number
                  example: 12345678901
                  required: false
                billingAuthorityReference:
                  type: string
                  description: Filters the results to include properties which are inside the provided billing authority.
                  required: true
                clientOrganisation:
                  type: string
                  description: client's organsiation name to filter by
                  required: false
                status:
                  type: string
                  enum: ["APPROVED", "PENDING", "DECLINED", "REVOKED", "MORE_EVIDENCE_REQUIRED"]
                  description: The status of a property link to filter by
                  required: false
                appointedFromDate:
                  type: date-only
                  example: 2020-01-31
                  description: Filters the results to include only property-links where appointedDate is on or after this date
                  required: false
                appointedToDate:
                  type: date-only
                  example: 2020-12-31
                  description: Filters the results to include only property-links where appointedDate is on or before this date
                  required: false
              responses:
                200:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/property-links/schemas/my-clients-property-links-response-schema.json
                      examples:
                        example-1:
                          value: !include endpoints/my-organisation/clients/property-links/examples/my-clients-property-links-response-example.json
            /{propertyLinkSubmissionId}:
              get:
                displayName: Get my client's property link
                description: !include endpoints/my-organisation/clients/property-links/get-my-clients-property-link-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                  projection:
                    type: string
                    enum: ["summary", "detailed"]
                    description: Currently accepts 'summary' and 'detailed' projection. Defaults to 'summary'.
                    required: false
                responses:
                  200:
                    body:
                      application/json:
                        type: !include endpoints/my-organisation/clients/property-links/schemas/my-clients-summary-property-link-response-schema.json
                        examples:
                          summary:
                            strict: true
                            description: Summary Property Link (?projection=summary)
                            value: !include endpoints/my-organisation/clients/property-links/examples/my-clients-summary-property-link-response-example.json
                          detailed:
                            strict: false
                            description: Detailed Property Link (?projection=detailed)
                            value: !include endpoints/my-organisation/clients/property-links/examples/my-clients-summary-property-link-response-example.json
              /evidence:
                post:
                  displayName: Attach property link evidence for a client
                  description: !include endpoints/my-organisation/clients/property-links/attach-client-property-link-evidence-overview.md
                  is: [headers.acceptHeader]
                  (annotations.scope): "all:business-rates"
                  securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                  queryParameters:
                  body:
                    application/json:
                      type: !include endpoints/my-organisation/clients/property-links/schemas/attach-client-property-link-evidence-request-schema.json
                      example: !include endpoints/my-organisation/clients/property-links/examples/attach-client-property-link-evidence-request-example.json
                  responses:
                    200:
                      body:
                        application/json:
                          type: !include endpoints/my-organisation/clients/property-links/schemas/attach-client-property-link-evidence-response-schema.json
                          examples:
                            example-1:
                              value: !include endpoints/my-organisation/clients/property-links/examples/attach-client-property-link-evidence-response-example.json
                /{evidenceReference}:
                  get:
                    displayName: Retrieve status of property link evidence for a client
                    description: !include endpoints/my-organisation/clients/property-links/get-client-property-link-evidence-overview.md
                    is: [headers.acceptHeader]
                    (annotations.scope): "all:business-rates"
                    securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                    queryParameters:
                    responses:
                      200:
                        body:
                          application/json:
                            type: !include endpoints/my-organisation/clients/property-links/schemas/get-client-property-link-evidence-response-schema.json
                            examples:
                              example-1:
                                value: !include endpoints/my-organisation/clients/property-links/examples/get-client-property-link-evidence-response-example.json
      /messages:
          get:
            displayName: Get messages summary
            description: !include endpoints/my-organisation/messages/get-my-organisations-messages-overview.md
            is: [headers.acceptHeader, paged, sortable]
            (annotations.scope): "all:business-rates"
            securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
            queryParameters:
              ccaCaseRef:
                type: string
                description: The ccaCaseRef of the check case
                required: false
              hereditamentAddress:
                type: string
                description: The address of the check case
                required: false
              ipOrganisationName:
                type: string
                description: The organisation the message relates to
                required: false
              isRead:
                type: boolean
                description: Filters the results to include only messages that have been read (true) or have not been read (false)
                required: false
              fromCreatedDateTime:
                type: datetime
                description: Filters the results to include only messages created on or after this datetime. Values must be in UTC format "YYYY-MM-DDThh:mm:ssZ". For example, 2019-02-28T16:30:00Z
                examples:
                 dateOnly:
                  value: 2019-02-28T00:00:00Z
                 dateTime:
                  value: 2019-02-28T16:41:41Z
                required: false
              toCreatedDateTime:
                type: datetime
                description: Filters the results to include only messages created on or before this datetime. Values must be in UTC format "YYYY-MM-DDThh:mm:ssZ". For example, 2019-02-28T16:30:00Z
                examples:
                 dateOnly:
                  value: 2019-02-28T00:00:00Z
                 dateTime:
                  value: 2019-02-28T16:41:41Z
                required: false
              sortField:
                type: string
                description: The sort field for the messages e.g CASEREF, EFFECTIVE_DATE, SUBJECT, ADDRESS, IP_ORGANISATION_NAME, LAST_READ_AT
                required: false
            responses:
              200:
                body:
                  application/json:
                    type: !include endpoints/my-organisation/messages/schemas/get-message-summary-response-schema.json
                    examples:
                      example-1:
                        value: !include endpoints/my-organisation/messages/examples/get-message-summary-response-example.json
          /{messageId}:
              get:
                displayName: Get message detailed
                description: !include endpoints/my-organisation/messages/get-my-organisations-messages-detailed-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                responses:
                  200:
                    body:
                      application/json:
                        type: !include endpoints/my-organisation/messages/schemas/get-message-detailed-response-schema.json
                        examples:
                          example-1:
                            value: !include endpoints/my-organisation/messages/examples/get-message-detailed-response-example.json
              post:
                displayName: Mark message as read
                description: !include endpoints/my-organisation/messages/mark-messages-read-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                responses:
                  204:
                    description: Message marked as read.
          /unreadCount:
              get:
                displayName: Get unread message count
                description: !include endpoints/my-organisation/messages/get-my-organisations-unread-message-count-overview.md
                is: [headers.acceptHeader]
                (annotations.scope): "all:business-rates"
                securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
                queryParameters:
                responses:
                  200:
                    body:
                      application/json:
                        type: !include endpoints/my-organisation/messages/schemas/get-unread-message-count-response-schema.json
                        examples:
                          example-1:
                            value: !include endpoints/my-organisation/messages/examples/get-unread-message-count-response-example.json
  /lookup-codes:
    /{lookupName}:
      get:
        displayName: Retrieve lookup values by type
        description: !include endpoints/lookups/lookups-overview.md
        is: [headers.acceptHeader]
        (annotations.scope): "all:business-rates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "all:business-rates" ] } ]
        queryParameters:
        responses:
          200:
            body:
              application/json:
                type: !include endpoints/lookups/schemas/lookups-response-schema.json
                examples:
                  example-1:
                    value: !include endpoints/lookups/examples/lookups-response-example.json
