#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: An overview

mediaType: application/hal+json

uses:
  sec: ../../../public/common/modules/securitySchemes.raml
  headers: ../../../public/common/modules/headers.raml

/hello:
  /application:
    get:
      displayName: Say hello application
      description: |
        A simple example for integrating with an application-restricted service, using your `server_token`.

        Any authorised request to this endpoint initiates a 'Hello Application' response.
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message": "Hello Application"
                }