#%RAML 1.0
---
title: Multiple methods
version: 1.0

/endpoint1:
    get:
      description: 1
      displayName: 1


/endpoint2:
    get:
      description: 2
      displayName: 2

/endpoint3:
    get:
      description: 3
      displayName: 3
