#%RAML 1.0
---
title: Hello World
version: 1.0

protocols: [ HTTPS ]
baseUri: https://helloworld.service.hmrc.gov.uk/

/hello:
  /there:
    put:
      displayName: Something
    get:
      displayName: SomethingElse
    options:
      displayName: TheOptions
    /{empref}:
        delete:
            displayName: killItWithFire
        /year:
             post:
                 displayName: updateyStuff
             /{taxYear}:
                 put:
                     displayName: placementStuff