queryParameters:
  page:
    description: "The results for this endpoint are paginated and this refers to the page number. </br> </br> Default: 1"
    type: integer
    required: false
  pageSize:
    description: "The results for this endpoint are paginated and this refers to the number of elements per page. </br> </br> Default: 15 </br> </br> Minimum: 10 </br> </br> Maximum: 100"
    type: integer
    required: false
