queryParameters:
  sortField:
    description: Field to sort the results by
    type: string
    required: false
  sortDirection:
    description: Results will be sorted in the specified direction (ascending or descending)
    type: string
    enum: [ "ASC", " DESC"]
    default: "ASC"
    required: false
